Feature/photo bulma
DOCMM-Solucoes/facil_facil_hospedagem pull request #101
Opened 2023-08-06 18:21 UTC by OsirisMariano

2023-08-06 20:28 UTC, osksergio approved these changes

2023-08-07 02:29 UTC, marcoaspeixoto approved these changes

2023-08-15 19:31 UTC, marcodotcastro requested changes
- [ ] Ajustar as routes de photos para structures
- [ ] Alinhar a identidade do nomes e icones

2023-08-22 19:27 UTC, marcodotcastro approved these changes

2023-08-22 19:47 UTC, merged