Feature/guide bulma
DOCMM-Solucoes/facil_facil_hospedagem pull request #98
Opened 2023-08-05 12:55 UTC by marcoaspeixoto

2023-08-06 23:55 UTC, osksergio approved these changes

2023-08-07 12:39 UTC, daniel-neves-dev approved these changes

2023-08-15 19:21 UTC, marcodotcastro requested changes
- [ ] Corrigir o phone
- [ ] Adicionar o botão editar no show
- [ ] Adicionar mais atributos no index

2023-08-22 19:16 UTC, marcodotcastro approved these changes

2023-08-22 19:25 UTC, merged